spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

    druid:
      aop-patterns: com.example.pojo.*  #??SpringBean
      filters: stat,wall  # ???????stat?sql????wall??????log4j????
      stat-view-servlet:  # ???????
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false0
      web-stat-filter:   # ??web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat: # ???filters???stat?????
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  redis:
    port: 6379
    client-type: jedis
    jedis:
      pool:
        max-active: 100